### Problem Statement Scenario:

Since the first automobile, the Benz Patent Motor Car in 1886, Mercedes-Benz has stood for important automotive innovations. These include the passenger safety cell with a crumple zone, the airbag, and intelligent assistance systems. Mercedes-Benz applies for nearly 2000 patents per year, making the brand the European leader among premium carmakers. Mercedes-Benz is the leader in the premium car industry. With a huge selection of features and options, customers can choose the customized Mercedes-Benz of their dreams.

To ensure the safety and reliability of every unique car configuration before they hit the road, the company’s engineers have developed a robust testing system. As one of the world’s biggest manufacturers of premium cars, safety and efficiency are paramount on Mercedes-Benz’s production lines. However, optimizing the speed of their testing system for many possible feature combinations is complex and time-consuming without a powerful algorithmic approach.

You are required to reduce the time that cars spend on the test bench. Others will work with a dataset representing different permutations of features in a Mercedes-Benz car to predict the time it takes to pass testing. Optimal algorithms will contribute to faster testing, resulting in lower carbon dioxide emissions without reducing Mercedes-Benz’s standards.

* If for any column(s), the variance is equal to zero, then you need to remove those variable(s).
* Check for null and unique values for test and train sets.
* Apply label encoder.
* Perform dimensionality reduction.
* Predict your test_df values using XGBoost.

In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)
data=pd.read_csv('C:\\Users\\hima ratheesh\\Downloads\\train.mercedez.csv')
data.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  X10  X11  X12  X13  X14  X15  X16  \
0   0  130.81   k  v  at  a  d  u  j  o    0    0    0    1    0    0    0   
1   6   88.53   k  t  av  e  d  y  l  o    0    0    0    0    0    0    0   
2   7   76.26  az  w   n  c  d  x  j  x    0    0    0    0    0    0    0   
3   9   80.62  az  t   n  f  d  x  l  e    0    0    0    0    0    0    0   
4  13   78.02  az  v   n  f  d  h  d  n    0    0    0    0    0    0    0   

   X17  X18  X19  X20  X21  X22  X23  X24  X26  X27  X28  X29  X30  X31  X32  \
0    0    1    0    0    1    0    0    0    0    0    0    0    0    1    0   
1    0    1    0    0    0    0    0    0    0    1    0    0    0    1    0   
2    1    0    0    0    0    0    0    0    0    1    1    1    0    1    0   
3    0    0    0    0    0    0    0    0    0    1    1    1    0    1    0   
4    0    0    0    0    0    0    0    0    0    1    1    1    0    1    0   

   X33  X34  X35  X36  X37  X38  X39  X40  X41  X42  X43  X44  X45  X46  X47  \
0    0    0    1    0    1    0    0    0    0    0    0    0    0    1    0   
1    0    0    1    0    1    0    0    0    0    0    0    0    0    0    0   
2    0    0    1    0    1    0    0    0    0    0    1    0    0    1    0   
3    0    0    1    0    1    0    0    0    0    0    1    0    0    1    0   
4    0    0    1    0    1    0    0    0    0    0    1    0    0    1    0   

   X48  X49  X50  X51  X52  X53  X54  X55  X56  X57  X58  X59  X60  X61  X62  \
0    0    0    0    0    0    0    0    0    0    0    1    0    0    0    0   
1    0    0    0    1    0    0    0    0    0    0    0    0    0    1    0   
2    0    0    0    1    0    0    1    0    0    0    1    0    0    1    0   
3    0    0    0    0    0    0    1    0    0    0    0    0    0    1    0   
4    0    0    0    1    0    0    1    0    0    0    0    0    0    1    0   

   X63  X64  X65  X66  X67  X68  X69  X70  X71  X73  X74  X75  X76  X77  X78  \
0    0    0    0    0    0    1    0    1    0    0    1    0    0    0    0   
1    0    0    0    0    0    0    0    1    0    0    1    0    0    0    0   
2    0    0    0    0    0    1    0    1    1    0    1    1    1    0    0   
3    0    0    0    0    0    0    0    1    1    0    1    0    1    0    0   
4    0    0    0    0    0    0    0    1    0    0    1    0    1    0    0   

   X79  X80  X81  X82  X83  X84  X85  X86  X87  X88  X89  X90  X91  X92  X93  \
0    0    0    0    0    0    0    1    0    0    0    0    0    0    0    0   
1    0    1    0    0    0    0    1    0    0    0    0    0    0    0    0   
2    0    1    0    0    0    1    1    0    0    0    0    0    0    0    0   
3    0    1    0    0    0    1    0    0    0    0    0    0    0    0    0   
4    0    1    0    0    0    0    0    0    0    0    0    0    0    0    0   

   X94  X95  X96  X97  X98  X99  X100  X101  X102  X103  X104  X105  X106  \
0    0    0    0    0    0    0     0     0     0     0     0     0     0   
1    0    0    1    0    1    0     1     1     0     0     0     0     0   
2    0    0    1    0    1    0     0     1     0     0     0     0     0   
3    0    0    1    0    1    0     0     1     0     0     0     0     0   
4    0    0    1    0    1    0     0     1     0     0     0     0     0   

   X107  X108  X109  X110  X111  X112  X113  X114  X115  X116  X117  X118  \
0     0     0     0     0     1     0     0     1     0     1     0     1   
1     0     0     0     0     1     0     0     0     0     0     0     1   
2     0     0     0     0     1     0     0     0     0     0     0     0   
3     0     1     0     0     1     0     0     1     0     0     0     0   
4     0     1     0     0     1     0     0     1     0     0     0     0   

   X119  X120  X122  X123  X124  X125  X126  X127  X128  X129  X130  X131  \
0     1     1     0     0     0     0     0     0     1     0     0     1   
1     1     1     0     0     0     0     0     1

In [2]:
data.shape

(4209, 378)

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB


In [4]:
pd.options.display.float_format='{:,.4f}'.format 
variance=data.var(numeric_only=True) 
variance=variance.reset_index() 
variance.columns=['id','values']

In [5]:
variance=variance.sort_values('values',ascending=1)
variance

id         values
315  X330         0.0000
279  X293         0.0000
276  X290         0.0000
275  X289         0.0000
97   X107         0.0000
332  X347         0.0000
254  X268         0.0000
83    X93         0.0000
221  X235         0.0000
219  X233         0.0000
283  X297         0.0000
3     X11         0.0000
193  X207         0.0002
243  X257         0.0002
196  X210         0.0002
30    X39         0.0002
324  X339         0.0002
245  X259         0.0002
24    X33         0.0002
177  X190         0.0002
266  X280         0.0002
85    X95         0.0002
246  X260         0.0002
33    X42         0.0002
274  X288         0.0002
256  X270         0.0002
191  X205         0.0002
281  X295         0.0002
190  X204         0.0002
282  X296         0.0002
354  X369         0.0005
304  X319         0.0005
368  X384         0.0005
113  X124         0.0005
357  X372         0.0005
255  X269         0.0005
7     X15         0.0005
264  X278         0.0005
222  X236         0.0005
141  X153         0.0007
31    X40         0.0007
64    X74         0.0007
317  X332         0.0007
50    X59         0.0007
79    X89         0.0007
231  X245         0.0007
303  X318         0.0007
238  X252         0.0007
82    X92         0.0009
77    X87         0.0009
100  X110         0.0009
155  X167         0.0009
73    X83         0.0012
342  X357         0.0012
351  X366         0.0012
148  X160         0.0012
263  X277         0.0014
252  X266         0.0014
248  X262         0.0014
134  X145         0.0014
239  X253         0.0014
234  X248         0.0014
76    X86         0.0014
172  X184         0.0014
51    X60         0.0014
369  X385         0.0014
367  X383         0.0017
81    X91         0.0017
94   X104         0.0019
58    X67         0.0019
199  X213         0.0019
16    X24         0.0019
292  X307         0.0021
56    X65         0.0021
257  X271         0.0021
338  X353         0.0021
244  X258         0.0024
179  X192         0.0024
95   X105         0.0024
267  X281         0.0026
8     X16         0.0026
295  X310         0.0026
13    X21         0.0026
112  X123         0.0026
185  X199         0.0028
226  X240         0.0028
350  X365         0.0028
102  X112         0.0028
349  X364         0.0028
114  X125         0.0031
213  X227         0.0031
320  X335         0.0036
268  X282         0.0040
171  X183         0.0040
297  X312         0.0043
87    X97         0.0043
285  X299         0.0045
21    X30         0.0045
27    X36         0.0045
284  X298         0.0045
153  X165         0.0045
17    X26         0.0050
216  X230         0.0052
46    X55         0.0052
240  X254         0.0052
25    X34         0.0054
198  X212         0.0054
310  X325         0.0057
68    X78         0.0057
53    X62         0.0059
160  X172         0.0059
202  X216         0.0059
157  X169         0.0066
186  X200         0.0066
355  X370         0.0066
223  X237         0.0066
92   X102         0.0068
225  X239         0.0068
44    X53         0.0068
323  X338         0.0068
200  X214         0.0068
78    X88         0.0071
305  X320         0.0071
294  X309         0.0071
229  X243         0.0071
111  X122         0.0071
80    X90         0.0073
228  X242         0.0073
84    X94         0.0073
203  X217         0.0073
235  X249         0.0075
302  X317         0.0075
9     X17         0.0075
366  X382         0.0075
10    X18         0.0078
326  X341         0.0080
207  X221         0.0080
365  X380         0.0080
89    X99         0.0085
329  X344         0.0085
253  X267         0.0089
278  X292         0.0089
308  X323         0.0092
364  X379         0.0094
293  X308         0.0094
161  X173         0.0096
260  X274         0.0099
182  X196         0.0101
277  X291         0.0103
23    X32         0.0110
54    X63         0.0113
35    X44         0.0113
288  X302         0.0113
32    X41         0.0113
181  X195         0.0115
67    X77         0.0124
38    X47         0.0127
96   X106         0.0129
48    X57         0.0131
2     X

* If for any column(s), the variance is equal to zero, then you need to remove those variable(s).

In [6]:
var=variance.loc[variance['values']<0.2,'id']
data1=data.drop(var,axis=1)
data1.drop('ID',axis=1,inplace=True)
data1.head()

y  X0 X1  X2 X3 X4 X5 X6 X8  X14  X27  X46  X51  X58  X64  X85  X100  \
0 130.8100   k  v  at  a  d  u  j  o    0    0    1    0    1    0    1     0   
1  88.5300   k  t  av  e  d  y  l  o    0    1    0    1    0    0    1     1   
2  76.2600  az  w   n  c  d  x  j  x    0    1    1    1    1    0    1     0   
3  80.6200  az  t   n  f  d  x  l  e    0    1    1    0    0    0    0     0   
4  78.0200  az  v   n  f  d  h  d  n    0    1    1    1    0    0    0     0   

   X115  X118  X119  X127  X132  X137  X156  X157  X163  X171  X178  X186  \
0     0     1     1     0     0     1     1     0     0     0     0     0   
1     0     1     1     1     1     0     1     0     0     0     1     0   
2     0     0     0     0     1     1     0     1     1     0     0     0   
3     0     0     0     0     1     0     0     1     0     0     0     0   
4     0     0     0     0     1     0     0     1     0     0     0     0   

   X187  X191  X194  X218  X220  X223  X224  X246  X250  X251  X261  X273  \
0     1     0     1     0     1     0     0     0     0     0     0     1   
1     1     0     1     0     0     0     0     0     1     0     0     1   
2     0     0     1     1     1     1     1     1     1     0     0     1   
3     0     0     1     1     1     1     0     1     1     0     0     1   
4     0     0     1     1     1     1     0     1     1     0     0     1   

   X311  X313  X314  X324  X329  X334  X337  X350  X351  X355  X358  X362  \
0     0     0     0     1     1     1     0     0     0     0     0     0   
1     1     0     0     0     1     0     1     0     0     0     0     0   
2     0     0     0     1     0     1     0     1     0     0     1     0   
3     0     0     0     0     0     0     0     1     0     0     1     0   
4     0     0     0     0     0     1     0     1     0     0     1     0   

   X375  X377  
0     0     1  
1     1     0  
2     0     0  
3     0     0  
4     0     0

In [7]:
data1.shape

(4209, 55)

### * Check for null and unique values for test and train sets.

In [8]:
data1[data1.isnull().any(axis=1)]

Empty DataFrame
Columns: [y, X0, X1, X2, X3, X4, X5, X6, X8, X14, X27, X46, X51, X58, X64, X85, X100, X115, X118, X119, X127, X132, X137, X156, X157, X163, X171, X178, X186, X187, X191, X194, X218, X220, X223, X224, X246, X250, X251, X261, X273, X311, X313, X314, X324, X329, X334, X337, X350, X351, X355, X358, X362, X375, X377]
Index: []

In [9]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Data columns (total 55 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   y       4209 non-null   float64
 1   X0      4209 non-null   object 
 2   X1      4209 non-null   object 
 3   X2      4209 non-null   object 
 4   X3      4209 non-null   object 
 5   X4      4209 non-null   object 
 6   X5      4209 non-null   object 
 7   X6      4209 non-null   object 
 8   X8      4209 non-null   object 
 9   X14     4209 non-null   int64  
 10  X27     4209 non-null   int64  
 11  X46     4209 non-null   int64  
 12  X51     4209 non-null   int64  
 13  X58     4209 non-null   int64  
 14  X64     4209 non-null   int64  
 15  X85     4209 non-null   int64  
 16  X100    4209 non-null   int64  
 17  X115    4209 non-null   int64  
 18  X118    4209 non-null   int64  
 19  X119    4209 non-null   int64  
 20  X127    4209 non-null   int64  
 21  X132    4209 non-null   int64  
 22  

In [10]:
data1.nunique()

y       2545
X0        47
X1        27
X2        44
X3         7
X4         4
X5        29
X6        12
X8        25
X14        2
X27        2
X46        2
X51        2
X58        2
X64        2
X85        2
X100       2
X115       2
X118       2
X119       2
X127       2
X132       2
X137       2
X156       2
X157       2
X163       2
X171       2
X178       2
X186       2
X187       2
X191       2
X194       2
X218       2
X220       2
X223       2
X224       2
X246       2
X250       2
X251       2
X261       2
X273       2
X311       2
X313       2
X314       2
X324       2
X329       2
X334       2
X337       2
X350       2
X351       2
X355       2
X358       2
X362       2
X375       2
X377       2
dtype: int64

In [11]:
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)
data2=pd.read_csv('C:\\Users\\hima ratheesh\\Downloads\\test.csv')
data2.head()

ID  X0 X1  X2 X3 X4 X5 X6 X8  X10  X11  X12  X13  X14  X15  X16  X17  X18  \
0   1  az  v   n  f  d  t  a  w    0    0    0    0    0    0    0    0    0   
1   2   t  b  ai  a  d  b  g  y    0    0    0    0    0    0    0    0    0   
2   3  az  v  as  f  d  a  j  j    0    0    0    0    1    0    0    0    0   
3   4  az  l   n  f  d  z  l  n    0    0    0    0    0    0    0    0    0   
4   5   w  s  as  c  d  y  i  m    0    0    0    0    1    0    0    0    0   

   X19  X20  X21  X22  X23  X24  X26  X27  X28  X29  X30  X31  X32  X33  X34  \
0    0    0    0    0    0    0    0    1    1    1    0    1    0    0    0   
1    1    0    0    0    0    0    0    1    0    0    0    1    0    0    0   
2    0    0    0    0    0    0    0    1    0    1    0    1    0    0    0   
3    0    0    0    0    0    0    0    1    1    1    0    1    0    0    0   
4    0    0    0    0    0    0    0    1    0    0    0    0    0    0    0   

   X35  X36  X37  X38  X39  X40  X41  X42  X43  X44  X45  X46  X47  X48  X49  \
0    1    0    1    0    0    0    0    0    1    0    0    1    0    0    0   
1    1    0    1    0    0    0    0    0    0    0    1    1    0    0    1   
2    1    0    1    0    0    0    0    0    0    0    0    0    0    0    0   
3    1    0    1    0    0    0    0    0    1    0    0    1    0    0    0   
4    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0   

   X50  X51  X52  X53  X54  X55  X56  X57  X58  X59  X60  X61  X62  X63  X64  \
0    0    0    0    0    1    0    0    0    0    0    0    1    0    0    0   
1    1    1    0    0    0    0    0    0    1    0    0    1    0    0    0   
2    0    1    0    0    1    0    0    0    1    0    0    1    0    0    0   
3    0    0    0    0    1    0    0    0    0    0    0    1    0    0    0   
4    0    1    0    0    0    0    0    0    1    0    0    1    0    0    1   

   X65  X66  X67  X68  X69  X70  X71  X73  X74  X75  X76  X77  X78  X79  X80  \
0    0    0    0    0    0    1    0    0    1    0    1    0    0    0    1   
1    0    0    0    0    0    1    0    0    1    0    0    0    0    0    1   
2    0    0    0    0    0    1    0    0    1    0    1    0    0    0    1   
3    0    0    0    0    0    1    0    0    1    0    1    0    0    0    1   
4    0    0    0    0    0    1    0    0    1    0    0    0    0    0    1   

   X81  X82  X83  X84  X85  X86  X87  X88  X89  X90  X91  X92  X93  X94  X95  \
0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0   
1    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0   
2    0    0    0    0    1    0    0    0    0    0    0    0    0    0    0   
3    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0   
4    0    0    0    0    1    0    0    0    0    0    0    0    0    0    0   

   X96  X97  X98  X99  X100  X101  X102  X103  X104  X105  X106  X107  X108  \
0    1    0    1    0     0     1     0     0     0     0     0     0     0   
1    0    0    1    0     0     1     0     1     0     0     0     0     0   
2    1    0    1    0     1     1     0     1     0     0     0     0     0   
3    1    0    1    0     0     1     0     0     0     0     0     0     0   
4    1    0    1    0     1     1     0     1     0     0     1     0     0   

   X109  X110  X111  X112  X113  X114  X115  X116  X117  X118  X119  X120  \
0     0     0     1     0     0     1     0     0     0     0     0     0   
1     0     0     1     0     0     0     0     1     0     1     1     1   
2     0     0     1     0     0     0     0     0     0     0     0     1   
3     0     0     1     0     0     1     0     0     0     0     0     1   
4     0     0     1     0     0     0     0     0     0     1     1     1   

   X122  X123  X124  X125  X126  X127  X128  X129  X130  X131  X132  X133  \
0     0     0     0     0     0     0     1     0     0     0     1     0   
1     0     0     0     0

In [12]:
data2.shape

(4209, 377)

In [13]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 377 entries, ID to X385
dtypes: int64(369), object(8)
memory usage: 12.1+ MB


In [14]:
data2[data2.isnull().any(axis=1)]

Empty DataFrame
Columns: [ID, X0, X1, X2, X3, X4, X5, X6, X8, X10, X11, X12, X13, X14, X15, X16, X17, X18, X19, X20, X21, X22, X23, X24, X26, X27, X28, X29, X30, X31, X32, X33, X34, X35, X36, X37, X38, X39, X40, X41, X42, X43, X44, X45, X46, X47, X48, X49, X50, X51, X52, X53, X54, X55, X56, X57, X58, X59, X60, X61, X62, X63, X64, X65, X66, X67, X68, X69, X70, X71, X73, X74, X75, X76, X77, X78, X79, X80, X81, X82, X83, X84, X85, X86, X87, X88, X89, X90, X91, X92, X93, X94, X95, X96, X97, X98, X99, X100, X101, X102, ...]
Index: []

In [15]:
data2.nunique()

ID      4209
X0        49
X1        27
X2        45
X3         7
X4         4
X5        32
X6        12
X8        25
X10        2
X11        2
X12        2
X13        2
X14        2
X15        2
X16        2
X17        2
X18        2
X19        2
X20        2
X21        2
X22        2
X23        2
X24        2
X26        2
X27        2
X28        2
X29        2
X30        2
X31        2
X32        2
X33        2
X34        2
X35        2
X36        2
X37        2
X38        2
X39        2
X40        2
X41        2
X42        2
X43        2
X44        2
X45        2
X46        2
X47        2
X48        2
X49        2
X50        2
X51        2
X52        2
X53        2
X54        2
X55        2
X56        2
X57        2
X58        2
X59        2
X60        2
X61        2
X62        2
X63        2
X64        2
X65        2
X66        2
X67        2
X68        2
X69        2
X70        2
X71        2
X73        2
X74        2
X75        2
X76        2
X77        2
X78        2
X79        2

### * Apply label encoder.

In [16]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Data columns (total 55 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   y       4209 non-null   float64
 1   X0      4209 non-null   object 
 2   X1      4209 non-null   object 
 3   X2      4209 non-null   object 
 4   X3      4209 non-null   object 
 5   X4      4209 non-null   object 
 6   X5      4209 non-null   object 
 7   X6      4209 non-null   object 
 8   X8      4209 non-null   object 
 9   X14     4209 non-null   int64  
 10  X27     4209 non-null   int64  
 11  X46     4209 non-null   int64  
 12  X51     4209 non-null   int64  
 13  X58     4209 non-null   int64  
 14  X64     4209 non-null   int64  
 15  X85     4209 non-null   int64  
 16  X100    4209 non-null   int64  
 17  X115    4209 non-null   int64  
 18  X118    4209 non-null   int64  
 19  X119    4209 non-null   int64  
 20  X127    4209 non-null   int64  
 21  X132    4209 non-null   int64  
 22  

In [17]:
data1.nunique()

y       2545
X0        47
X1        27
X2        44
X3         7
X4         4
X5        29
X6        12
X8        25
X14        2
X27        2
X46        2
X51        2
X58        2
X64        2
X85        2
X100       2
X115       2
X118       2
X119       2
X127       2
X132       2
X137       2
X156       2
X157       2
X163       2
X171       2
X178       2
X186       2
X187       2
X191       2
X194       2
X218       2
X220       2
X223       2
X224       2
X246       2
X250       2
X251       2
X261       2
X273       2
X311       2
X313       2
X314       2
X324       2
X329       2
X334       2
X337       2
X350       2
X351       2
X355       2
X358       2
X362       2
X375       2
X377       2
dtype: int64

In [18]:
#char=data1.select_dtypes(exclude='number')
#num=data1.select_dtypes(include='number')

In [19]:
#char1=pd.get_dummies(char.astype(str),drop_first=True)
#char1.head()

In [21]:
#char

In [22]:
from sklearn import preprocessing
label_encoder=preprocessing.LabelEncoder()

In [23]:
data1['X0']=label_encoder.fit_transform(data1['X0'])

In [24]:
data1['X0'].unique()

array([32, 20, 40,  9, 36, 43, 31, 29, 39, 35, 19, 27, 44, 45,  7,  8, 10,
       46, 37, 15, 12, 42,  5,  0, 26,  6, 25, 13, 24,  1, 22, 14, 30, 38,
       21, 18, 23, 41,  4, 16, 34, 33, 17, 11,  3, 28,  2])

In [25]:
data1['X1'] =label_encoder.fit_transform(data1['X1'])
data1['X1'].unique()

array([23, 21, 24,  3, 19, 13, 20,  1,  4,  0,  6,  9, 26, 11, 16, 22, 17,
       15, 10, 25,  5,  7, 14, 12,  8, 18,  2])

In [26]:
data1['X2'] =label_encoder.fit_transform(data1['X2'])
data1['X2'].unique()

array([17, 19, 34, 25, 16, 14, 38,  7,  8, 33,  0, 31,  3, 39, 26, 24,  5,
       21,  2, 13, 27, 29, 20, 42, 22, 12,  9, 28, 41, 18, 40, 11, 43,  6,
       36, 10, 30, 37,  4, 32,  1, 23, 35, 15])

In [27]:
data1['X3'] =label_encoder.fit_transform(data1['X3'])
data1['X3'].unique()

array([0, 4, 2, 5, 3, 1, 6])

In [28]:
data1['X4'] =label_encoder.fit_transform(data1['X4'])
data1['X4'].unique()

array([3, 1, 2, 0])

In [29]:
data1['X5'] =label_encoder.fit_transform(data1['X5'])
data1['X5'].unique()

array([24, 28, 27, 12, 11, 10, 14, 13,  9,  8,  5,  6,  1,  2,  3,  4,  7,
       16, 15, 18, 17, 20, 21, 23, 22, 25, 26, 19,  0])

In [30]:
data1['X6'] =label_encoder.fit_transform(data1['X6'])
data1['X6'].unique()

array([ 9, 11,  3,  7,  8,  0,  6,  2, 10,  4,  5,  1])

In [31]:
data1['X8'] =label_encoder.fit_transform(data1['X8'])
data1['X8'].unique()

array([14, 23,  4, 13, 18,  0,  7, 15, 12, 10,  3,  8, 21,  9,  1, 16, 22,
        6, 24, 11,  5, 20, 17, 19,  2])

### * Perform dimensionality reduction

In [32]:
data1.shape

(4209, 55)

In [33]:
#scaling the data
from sklearn import preprocessing
data1_scaled=preprocessing.scale(data1)

In [34]:
from sklearn.decomposition import PCA

In [35]:
pca=PCA(n_components=2).fit(data1)
data_pca=pca.transform(data1)
data_pca.shape,data1.shape


((4209, 2), (4209, 55))

### * Predict your test_df values using XGBoost.

In [36]:
X=data1.drop('y',axis=1)
y=data1.loc[:,'y']

In [37]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=123)

In [38]:
import xgboost as xg
xgb_r=xg.XGBRegressor(objective='reg:squarederror',n_estimators=10,seed=123)


In [39]:
#fitting the model:
xgb_r.fit(X_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=10, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [40]:
y_pred=xgb_r.predict(X_test)

In [41]:
d=pd.DataFrame()
d['y_test']=y_test
d['y_pred']=y_pred
d['mp']=abs((d['y_test']-d['y_pred'])/d['y_test'])
(d.mp.mean())*100

5.368762608039641

In [42]:
# We are getting mape of 5.36.